<a href="https://colab.research.google.com/github/Amirtha-006/Artifical-inteligience/blob/main/Artifical_intellligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pdf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df=pd.read_csv('/content/heart_disease_health_indicators_BRFSS2015.csv')

df.head()

df.info()

df.isnull().sum()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   HeartDiseaseorAttack  253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   Diabetes              253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

HeartDiseaseorAttack    0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
Diabetes                0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [ ]:
obj_list=df.select_dtypes(include='object').columns
obj_list



Index([], dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for obj in obj_list:
         of[obj] = le.fit_transform(df[obj].astype(str))
df.head()

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0       0.0           0.0     0.0  ...            1.0          0.0      5.0   
1       0.0           1.0     0.0  ...            0.0          1.0      3.0   
2       0.0           0.0     1.0  ...            1.0          1.0      5.0   
3       0.0           1.0     1.0  ...            1.0          0.0      2.0   
4       0.0           1.0     1.0  ...            1.0          0.0      2.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4       3.0       0.0       0.0  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [ ]:
correlation=df.corr()
correlation

HeartDiseaseorAttack    HighBP  HighChol  CholCheck  \
HeartDiseaseorAttack              1.000000  0.209361  0.180765   0.044206   
HighBP                            0.209361  1.000000  0.298199   0.098508   
HighChol                          0.180765  0.298199  1.000000   0.085642   
CholCheck                         0.044206  0.098508  0.085642   1.000000   
BMI                               0.052904  0.213748  0.106722   0.034495   
Smoker                            0.114441  0.096991  0.091299  -0.009929   
Stroke                            0.203002  0.129575  0.092620   0.024158   
Diabetes                          0.180272  0.271596  0.209085   0.067546   
PhysActivity                     -0.087299 -0.125267 -0.078046   0.004190   
Fruits                           -0.019790 -0.040555 -0.040859   0.023849   
Veggies                          -0.039167 -0.061266 -0.039874   0.006121   
HvyAlcoholConsump                -0.028991 -0.003972 -0.011543  -0.023730   
AnyHealthcare                     0.018734  0.038425  0.042230   0.117626   
NoDocbcCost                       0.031000  0.017358  0.013310  -0.058255   
GenHlth                           0.258383  0.300530  0.208426   0.046589   
MentHlth                          0.064621  0.056456  0.062069  -0.008366   
PhysHlth                          0.181698  0.161212  0.121751   0.031775   
DiffWalk                          0.212709  0.223618  0.144672   0.040585   
Sex                               0.086096  0.052207  0.031205  -0.022115   
Age                               0.221618  0.344452  0.272318   0.090321   
Education                        -0.099600 -0.141358 -0.070802   0.001510   
Income                           -0.141011 -0.171235 -0.085459   0.014259   

                           BMI    Smoker    Stroke  Diabetes  PhysActivity  \
HeartDiseaseorAttack  0.052904  0.114441  0.203002  0.180272     -0.087299   
HighBP                0.213748  0.096991  0.129575  0.271596     -0.125267   
HighChol              0.106722  0.091299  0.092620  0.209085     -0.078046   
CholCheck             0.034495 -0.009929  0.024158  0.067546      0.004190   
BMI                   1.000000  0.013804  0.020153  0.224379     -0.147294   
Smoker                0.013804  1.000000  0.061173  0.062914     -0.087401   
Stroke                0.020153  0.061173  1.000000  0.107179     -0.069151   
Diabetes              0.224379  0.062914  0.107179  1.000000     -0.121947   
PhysActivity         -0.147294 -0.087401 -0.069151 -0.121947      1.000000   
Fruits               -0.087518 -0.077666 -0.013389 -0.042192      0.142756   
Veggies              -0.062275 -0.030678 -0.041124 -0.058972      0.153150   
HvyAlcoholConsump    -0.048736  0.101619 -0.016950 -0.057882      0.012392   
AnyHealthcare        -0.018471 -0.023251  0.008776  0.015410      0.035505   
NoDocbcCost           0.058206  0.048946  0.034804  0.035436     -0.061638   
GenHlth               0.239185  0.163143  0.177942  0.302587     -0.266186   
MentHlth              0.085310  0.092196  0.070172  0.073507     -0.125587   
PhysHlth              0.121141  0.116460  0.148944  0.176287     -0.219230   
DiffWalk              0.197078  0.122463  0.176567  0.224239     -0.253174   
Sex                   0.042950  0.093662  0.002978  0.031040      0.032482   
Age                  -0.036618  0.120641  0.126974  0.185026     -0.092511   
Education            -0.103932 -0.161955 -0.076009 -0.130517      0.199658   
Income               -0.100069 -0.123937 -0.128599 -0.171483      0.198539   

                        Fruits  ...  AnyHealthcare  NoDocbcCost   GenHlth  \
HeartDiseaseorAttack -0.019790  ...       0.018734     0.031000  0.258383   
HighBP               -0.040555  ...       0.038425     0.017358  0.300530   
HighChol             -0.040859  ...       0.042230     0.013310  0.208426   
CholCheck             0.023849  ...       0.117626    -0.058255  0.046589   
BMI                  -0.087518  ...      -0.018471     0.058206  0.239

In [ ]:
x = df.drop('HeartDiseaseorAttack' , axis=1).values
y = df['HeartDiseaseorAttack'].values
from sklearn.model_selection import train_test_split
np.random.seed(41)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier().fit(x_train,y_train)
knn.score(x_test,y_test)

0.8958793230316409

In [ ]:
from sklearn.linear_model import LogisticRegression
np.random.seed(41)
lr = LogisticRegression().fit(x_train,y_train)
lr.score(x_test,y_test)

0.9067328918322296

In [ ]:
from sklearn .ensemble import RandomForestClassifier
np.random.seed(41)
rf = RandomForestClassifier().fit(x_train,y_train)
rf.score(x_test,y_test)

0.9016608851045937

In [ ]:
from sklearn.metrics import confusion_matrix
prediction=lr.predict(x_test)
prediction
confusion_matrix=confusion_matrix(y_test,prediction)
confusion_matrix

array([[68161,   740],
       [ 6358,   845]])

In [ ]:
from sklearn.metrics import confusion_matrix
prediction=knn.predict(x_test)
prediction
confusion_matrix=confusion_matrix(y_test,prediction)
confusion_matrix

array([[67430,  1471],
       [ 6453,   750]])

In [ ]:
from sklearn.metrics import confusion_matrix
prediction=rf.predict(x_test)
prediction
confusion_matrix=confusion_matrix(y_test,prediction)
confusion_matrix

array([[67822,  1079],
       [ 6405,   798]])

In [ ]:
y=df.HeartDiseaseorAttack.values
x=df.drop(['HeartDiseaseorAttack'],axis=1)
x

HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  Diabetes  \
0          1.0       1.0        1.0  40.0     1.0     0.0       0.0   
1          0.0       0.0        0.0  25.0     1.0     0.0       0.0   
2          1.0       1.0        1.0  28.0     0.0     0.0       0.0   
3          1.0       0.0        1.0  27.0     0.0     0.0       0.0   
4          1.0       1.0        1.0  24.0     0.0     0.0       0.0   
...        ...       ...        ...   ...     ...     ...       ...   
253675     1.0       1.0        1.0  45.0     0.0     0.0       0.0   
253676     1.0       1.0        1.0  18.0     0.0     0.0       2.0   
253677     0.0       0.0        1.0  28.0     0.0     0.0       0.0   
253678     1.0       0.0        1.0  23.0     0.0     0.0       0.0   
253679     1.0       1.0        1.0  25.0     0.0     0.0       2.0   

        PhysActivity  Fruits  Veggies  ...  AnyHealthcare  NoDocbcCost  \
0                0.0     0.0      1.0  ...            1.0          0.0   
1                1.0     0.0      0.0  ...            0.0          1.0   
2                0.0     1.0      0.0  ...            1.0          1.0   
3                1.0     1.0      1.0  ...            1.0          0.0   
4                1.0     1.0      1.0  ...            1.0          0.0   
...              ...     ...      ...  ...            ...          ...   
253675           0.0     1.0      1.0  ...            1.0          0.0   
253676           0.0     0.0      0.0  ...            1.0          0.0   
253677           1.0     1.0      0.0  ...            1.0          0.0   
253678           0.0     1.0      1.0  ...            1.0          0.0   
253679           1.0     1.0      0.0  ...            1.0          0.0   

        GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0           5.0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1           3.0       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2           5.0      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3           2.0       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4           2.0       3.0       0.0       0.0  0.0  11.0        5.0     4.0  
...         ...       ...       ...       ...  ...   ...        ...     ...  
253675      3.0       0.0       5.0       0.0  1.0   5.0        6.0     7.0  
253676      4.0       0.0       0.0       1.0  0.0  11.0        2.0     4.0  
253677      1.0       0.0       0.0       0.0  0.0   2.0        5.0     2.0  
253678      3.0       0.0       0.0       0.0  1.0   7.0        5.0     1.0  
253679      2.0       0.0       0.0       0.0  0.0   9.0        6.0     2.0  

[253680 rows x 21 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train=x_train.T
x_test=x_test.T
y_train=y_train.T
y_test=y_test.T


from sklearn.linear_model import LogisticRegression
accuracies=()
lr=LogisticRegression()
lr.fit(x_train.T,y_train.T)
acc=lr.score(x_test.T,y_test.T)*100
print('Test accuracy {:.2f}%'.format(acc))

Test accuracy 90.80%
